language: node_js
notifications:
  email: false
node_js:
  - 'node'
  - '6'
script: npm start validate
after_success:
  - npm install -g codecov semantic-release
  - codecov
  - npm run semantic-release
  - npm publish
branches:
  except: /^v\d+\.\d+\.\d+$/
